# Generated by Django 4.1.8 on 2023-05-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishment',
            old_name='photos',
            new_name='loc_picture',
        ),
    ]
