# Generated by Django 4.1.8 on 2023-05-18 03:46

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='accommodations',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
