# Generated by Django 4.1.8 on 2023-05-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_picture',
            field=models.CharField(max_length=999999999),
        ),
    ]
