# Generated by Django 4.1.8 on 2023-05-18 03:51

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_establishment_accommodations'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='reviews',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
