# Generated by Django 4.1.8 on 2023-04-27 18:41

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(help_text='Please enter a valid email address', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='IDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=50)),
                ('id_picture', models.URLField()),
                ('id_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=1)),
                ('suffix', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('accommodations', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('verified', models.BooleanField()),
                ('archived', models.BooleanField()),
                ('tickets', djongo.models.fields.JSONField()),
                ('contact_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.contactdetails')),
                ('id_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.idverification')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.name')),
                ('user_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('dateSubmited', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('archived', models.BooleanField()),
                ('body', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
